spring:
  application:
    name: helpers-service
  datasource:
    url: postgres://chbwwuawarfvvg:5f57dbbcc4f1f20325861c2cca432caee098f47357319778cdac629f71eef9ce@ec2-3-234-109-123.compute-1.amazonaws.com:5432/d2vkk65nfe09vu
    username: chbwwuawarfvvg
    password: 5f57dbbcc4f1f20325861c2cca432caee098f47357319778cdac629f71eef9ce
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: GMT-3
    show-sql: true
google:
  url: https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&
  key: AIzaSyDFFCp3z5fdG6S89FGFAZKanlvaQ7YlUbI
  distance: 5000